config/routes.rb
Rails.application.routes.draw do
  resource :login

  resources :tweets

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_logged_in
    return true if current_user

    redirect_to login_path, notice: 'please log in to do that'
    return false
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def show
  end

  def create
    u = User.
      find_by(username: params[:username]).
      try(:authenticate, params[:password])

    if u
      session[:user_id] = u.id
      return redirect_to tweets_path
    end

    redirect_to(login_path, notice: 'wrong login info, try again')
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in, only: %i{new create}

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html do
          redirect_to tweets_path, notice: 'Tweet was successfully created.'
        end
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:body)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bryceapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <p id="user">
    Logged in as
    <%= current_user.username %>
  </p>
<% else %>
  <p id="login">
    You're not logged in.
    <%= link_to 'Log in here!', login_path %>
  </p>
<% end %>

<p id="notice"><%= notice %></p>


<%= yield %>

</body>
</html>

app/views/logins/index.html.erb
<h1>Logins#index</h1>
<p>Find me in app/views/logins/index.html.erb</p>

app/views/logins/show.html.erb
<%= form_tag do %>
  <p>
    <%= label_tag :username %>
    <%= text_field_tag :username %>
  </p>
  <p>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </p>
  <p>
    <%= submit_tag 'Log in' %>
  </p>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.user.try(:username) %></td>
        <td><%= tweet.body %></td>
        <td>
          <%= link_to tweet do %>
            <%= time_ago_in_words(tweet.created_at) %>
            ago
          <% end %>
        </td>
        <td><%= link_to 'Delete forever', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p>
  <%= @tweet.body %>
</p>
<p>
  <%= time_ago_in_words @tweet.created_at %> ago
  /
  <%= @tweet.created_at.localtime.to_formatted_s(:long_ordinal) %>
</p>

<%= link_to 'Back', tweets_path %>